spring:
  application:
    name: NotificationsService
mail:
  host: smtp.gmail.com
  port: 587
  username: firewesh@gmail.com
  password: lvqz jirb kjwe dtpr
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
server:
  port: 8082
