spring:
  application:
    name: NotificationsService
  mail:
    host: smtp.gmail.com
    port: 587
    username: firewesh@gmail.com
    password: lvqz jirb kjwe dtpr
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
  artemis:
    broker-url: tcp://localhost:61616
    user: artemis
    password: artemis
    mode: native
  jms:
    cache:
      enabled: false
server:
  port: 8082
